### ISSUE TITLE
Elementor crash

### ISSUE THREAD

**Issue by error414** [andresdominguez/elementor#34]
Hi,

elementor crash when I try click to DOM node in inspector.

1) webdriver-manager start     log here:http://pastebin.com/KmV2MS9r
2) elementor http://localhost:63342/rcitimer/main_window.html log here: http://pastebin.com/TCssiDYw
3) I open devel tools on google chrome
4) "elements" and than "protractors" and than I select some node in DOM and elementor crash

Here is video what happened. https://youtu.be/SmKh6acTjIY

**Comment by goldhamerjb** [comment]
I just installed Elementor for the first time today and I am getting the exact same problem. I tried it with 1.1.0 and 1.0.10 versions.

**Comment by repose84** [comment]
I am also facing the exact same issue like @error414. Is there any fix available ?

**Comment by andresdominguez** [comment]
Thank you for reporting this issue. The problem is that protractor uses the developer tools to communicate with the browser. If you want to use the developer tools feature you need to open a second tab that points to the same URL with the view in the same state. You will explore on the second tab, but protractor will test the selectors on the first tab.

There is known workaround. I have discussed this with the protractor team.
